### ISSUE TITLE
Separate xpath expression compilation

### ISSUE THREAD

**Issue by tv42** [antchfx/htmlquery#15]
Hi. This package seems hard to use if you want init-time compilation of xpath expressions, like https://godoc.org/github.com/antchfx/xpath#MustCompile -- `Find` and `FindOne` don't take `*xpath.Expr`, and have some unexported logic that seems relevant for html.

Separate xpath expression compilation would also help avoid the case where currently if one gives user input to `Find`/`FindOne`, they can panic.

**Comment by zhengchun** [comment]
Hello, Thanks for your feedback.

Can you point to are unexposed methods for html? So that I can add it to the library if these can help.

`Find` and `FindOne` are not accept `xpath.Expr` as function's parameter because `xpath.Expr` is not can re-used object, If accept  `xpath.Expr`  as parameter will made the user consider this object can as static object re-used in the next query. https://github.com/antchfx/xmlquery/pull/18#issuecomment-535580095

In the Past, some people also point to the `Find` and `FindOne` will panic an error if they input invalid XPath expression. I'm considering `return  nil` if the input XPath is not correct. or add new method for find and test these XPath, Like this

```go
func Query(top *html.Node, expr string) ([]*html.Node,error){
exp, err := xpath.Compile(expr)
if err != nil {
    return nil,err
}
...
return nodes,nil
}
```
What do you think?

**Comment by tv42** [comment]
`Find` and `FindOne` both do postprocessing of the result using `getCurrentNode`.

`xpath.Expr` is not reusable? That's really surprising, and not documented at all. Why does it expose a separate compilation step then? The current API and naming makes it feel like `regexp.Compile` -- I've never seen a system where executing a query mutates the query.

Yes, adding an error return would be a trivial change, and let callers decide how to handle things.

**Comment by zhengchun** [comment]
`xpath.Expr`  originally design goal is for reusable object like the `regexp` object, But it is hasn't be  implemented yet.

**Comment by zhengchun** [comment]
Sorry, I made a mistake. I am checked code again and found I already implemented `xpath.Expr` reusable feature. https://github.com/antchfx/xpath/issues/6 ,It's too long ago, I has forget.

**Comment by tv42** [comment]
Tested & working!
