### ISSUE TITLE
Switch to SemVer

### ISSUE THREAD

**Issue by misha-plus** [antchfx/htmlquery#9]
Hello.
I'm started using Colly but your library changed the interface.
It will good to switch htmlquery to SemVer to avoid this in future

This is the reason https://github.com/gocolly/colly/issues/282

Thank you

**Comment by zhengchun** [comment]
I'm so sorry, a few days ago, I'm removed a `FindEach()` and `FindEachWithBreak()`, #7 , because plan to release 1.0 version, another reason is `Find()` will return unique element, you need implement yourself FindEach. I will switch to SemVer or tag release to avoid this, thanks for your suggestion.
